environments:
  # 是否开启调试输出
  debug: true
  # 服务地址端口配置
  server: 0.0.0.0:7125
    # 用户配置项
  user:
    # 重置密码链接的有效时间 单位(s)
    reset_expires: 3600
  # JWT配置项
  jwt:
    # 自定义签名密钥 不能公开 建议使用随机串
    sign_key: R29QYW4=
    # 强制使用HMAC-SHA族 [HS256 HS348 HS512] 默认 HS256
    sign_method: HS256
    # 签名发布者
    sign_issuer: GraduationProject
    # 签名主题
    sign_subject: Login
    # Token 有效时间 单位:秒
    sign_expires: 3600
  mysql:
    # MySQL Data Source Name
    dsn: root:11ysc1s1kR@tcp(172.16.174.128:33061)/bs?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local
    # 是否开启 ORM 的调试
    debug: true
  redis:
    # Redis Data Source Name
    # docker: docker run -d --name go-redis -p 6379:6379 redis --requirepass "11ysc1s1kR"
    # 填写格式: password@host:port
    dsn: 11ysc1s1kR@172.16.174.128:6379
    # 是否开启 Redis 的调试信息
    debug: true
    # 邮件服务功能配置
  email:
    # 邮件发送服务STMP地址 host
    server_host: smtp.yeah.net
    # STMP端口
    server_port: 465
    # 发送者名称
    from_email: xuthus5@yeah.net
    # 发送者昵称别名
    from_user: GoPan
    # 发送者密码
    from_password: ZWJQRFdkM1B0a3li