version: "3.7"
services:
    db:
        image: mysql:8
        restart: always
        container_name: togo_mysql_8
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: togo
    project:
        build: ./
        restart: always
        container_name: togo_server
        volumes:
            - "./:/Project"
        depends_on:
            - db
        ports:
            - "5000:5000"
        links:
            - db:mysql_c
